name: Check RiotPhroxzon Tweets

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 7-9 * * *"

jobs:
  check-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # No usar download-artifact para evitar error

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snscrape requests

      - name: Run bot once
        run: python bot.py

