name: Check RiotPhroxzon Tweets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # todos los días a las 7 AM UTC

jobs:
  check_tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install snscrape requests

      - name: Run script
        run: python bot.py
